table dim_produto_raw
	lineageTag: d95d7939-8aa8-4832-81ee-5e3ca926aece

	column id_produto
		dataType: int64
		formatString: 0
		lineageTag: d26bcff4-e53e-4cd0-bb5c-b6f72ba480e7
		summarizeBy: none
		sourceColumn: id_produto

		annotation SummarizationSetBy = Automatic

	column sku
		dataType: string
		lineageTag: b7bb6c51-4d71-473d-8b68-7cd33c38de97
		summarizeBy: none
		sourceColumn: sku

		annotation SummarizationSetBy = Automatic

	column descricao
		dataType: string
		lineageTag: 74dfe7f3-6a10-4e46-8b08-e25f6689444d
		summarizeBy: none
		sourceColumn: descricao

		annotation SummarizationSetBy = Automatic

	column categoria
		dataType: string
		lineageTag: c7524113-7e70-42d9-86df-89a2da485710
		summarizeBy: none
		sourceColumn: categoria

		annotation SummarizationSetBy = Automatic

	column veiculo_aplicacao
		dataType: string
		lineageTag: 7c7e8ff4-e8f5-4ce3-8b1b-274049808203
		summarizeBy: none
		sourceColumn: veiculo_aplicacao

		annotation SummarizationSetBy = Automatic

	column peso_kg
		dataType: double
		lineageTag: a037207d-831a-4549-896d-f284c6bcd52e
		summarizeBy: none
		sourceColumn: peso_kg

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column custo_unit_usd
		dataType: double
		lineageTag: 8b9171b1-e395-4268-9335-1a4c9641cec1
		summarizeBy: none
		sourceColumn: custo_unit_usd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column preco_unit_brl
		dataType: double
		lineageTag: f066322d-3a95-4308-b0f5-2218b17ed272
		summarizeBy: none
		sourceColumn: preco_unit_brl

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column qtd_por_embalagem
		dataType: int64
		formatString: 0
		lineageTag: 2353c1d6-1e23-4e3c-8486-0c74d02d5a34
		summarizeBy: none
		sourceColumn: qtd_por_embalagem

		annotation SummarizationSetBy = Automatic

	partition dim_produto_raw = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\dansi\Desktop\Material\raw\dim_produto_raw.csv"),[Delimiter=";", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id_produto", Int64.Type}, {"sku", type text}, {"descricao", type text}, {"categoria", type text}, {"veiculo_aplicacao", type text}, {"peso_kg", type number}, {"custo_unit_usd", type number}, {"preco_unit_brl", type number}, {"qtd_por_embalagem", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

