table dim_cliente_raw
	lineageTag: a0020a79-d2a1-48f7-ba40-168ea4d9d756

	column id_cliente
		dataType: int64
		formatString: 0
		lineageTag: 99a789d3-a98e-4e52-9550-e81b8738145b
		summarizeBy: none
		sourceColumn: id_cliente

		annotation SummarizationSetBy = Automatic

	column nome_cliente
		dataType: string
		lineageTag: ddf2846e-caa1-4012-8be2-520cef28a067
		summarizeBy: none
		sourceColumn: nome_cliente

		annotation SummarizationSetBy = Automatic

	column cnpj
		dataType: string
		lineageTag: b86e67f0-478a-4bc0-8790-70655644a7b8
		summarizeBy: none
		sourceColumn: cnpj

		annotation SummarizationSetBy = Automatic

	column tipo_cliente
		dataType: string
		lineageTag: 03a2dcde-6cdb-4b81-aa23-fdf315d31054
		summarizeBy: none
		sourceColumn: tipo_cliente

		annotation SummarizationSetBy = Automatic

	column uf
		dataType: string
		lineageTag: 2d2f2646-48a1-4a8b-8577-9eb664b904b3
		summarizeBy: none
		sourceColumn: uf

		annotation SummarizationSetBy = Automatic

	column uf_nome
		dataType: string
		lineageTag: 03da5bd7-6865-43b6-b0ef-676209103f6e
		summarizeBy: none
		sourceColumn: uf_nome

		annotation SummarizationSetBy = Automatic

	column cidade
		dataType: string
		lineageTag: cac5bce9-5a40-4b49-a622-5250c4737397
		summarizeBy: none
		sourceColumn: cidade

		annotation SummarizationSetBy = Automatic

	column limite_credito_brl
		dataType: int64
		formatString: 0
		lineageTag: 3edea581-5569-4162-a10c-8b863125e6ec
		summarizeBy: sum
		sourceColumn: limite_credito_brl

		annotation SummarizationSetBy = Automatic

	column data_cadastro
		dataType: dateTime
		formatString: Long Date
		lineageTag: d885cf58-a1db-428c-a23a-03e4a1497241
		summarizeBy: none
		sourceColumn: data_cadastro

		variation Variation
			isDefault
			relationship: db8ca7d6-697f-46e4-a937-d72e8d4a6b8c
			defaultHierarchy: LocalDateTable_a722bfc2-887a-48a5-bd2f-c768c068059d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition dim_cliente_raw = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\dansi\Desktop\Material\raw\dim_cliente_raw.csv"),[Delimiter=";", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id_cliente", Int64.Type}, {"nome_cliente", type text}, {"cnpj", type text}, {"tipo_cliente", type text}, {"uf", type text}, {"uf_nome", type text}, {"cidade", type text}, {"limite_credito_brl", Int64.Type}, {"data_cadastro", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

